### ISSUE TITLE
Check Gapple Cooldown

### ISSUE THREAD

**Issue by Michael-Ziluck** [ZiluckMichael/HCF#57]
Self expanatory, puts a cooldown on Notch apples/God apples. Configurable cooldown should be included as a timer in the scoreboard

**Comment by ctooley21** [comment]
Looks to be done in handler class GappleHandler

**Comment by Michael-Ziluck** [comment]
The issue involves making sure the code is good, not that it's there

**Comment by Michael-Ziluck** [comment]
Rewritten
