### ISSUE TITLE
Check if looting-buffer exists in config.yml

### ISSUE THREAD

**Issue by Michael-Ziluck** [ZiluckMichael/HCF#83]
It's used in LootingBuffHandler. Want to make sure it's there. Also check with Justin if it's still wanted.

**Comment by ctooley21** [comment]
@ZiluckMichael it does exist within the HCF config, but is attempting to get the value from DesireCore which hasn't had a config setup yet.

**Comment by ctooley21** [comment]
Justin said he wants to use it as well.

**Comment by Michael-Ziluck** [comment]
Moved the config over
